[package]
name = "akgine"
version = "0.1.7"
edition = "2024"
description = "Global function"
license = "GPL-3.0-only"
repository = "https://github.com/Arflaka/akgine"

[lib]
name = "akgine"
crate-type = ["cdylib", "rlib"] # required for Android .so

[lints.rust]
unused_parens = "allow"

[dependencies]
akgine_macros = { path = "./akgine_macros", version = "0.1.3", optional = true }
serde_json = { version = "1.0.151", optional = true }
egui_extras = { version = "0.36.2", features = ["image"], optional = true }
serde = { version = "1.0.229", features = ["derive"], optional = true }
rusqlite = { version = "0.40.2", features = ["bundled"], optional = true }
tiny_http = { version = "0.12", optional = true }

[features]
default = ["derive", "database"]                           # Aucune feature n'est activée par défaut
derive = ["dep:akgine_macros"]
gui = ["dep:egui_extras", "dep:eframe"]
database = ["dep:serde", "dep:serde_json", "dep:rusqlite"]
web = ["dep:tiny_http"]

[target.'cfg(not(target_os = "android"))'.dependencies]
eframe = { version = "0.36.2", default-features = false, optional = true, features = [
    "default_fonts",
    "glow",
    "persistence",
] }

# eframe SANS les features desktop/accesskit quand on build Android
[target.'cfg(target_os = "android")'.dependencies]
eframe = { version = "0.36.2", default-features = false, optional = true, features = [
    "default_fonts",
    "android-native-activity",
    "glow",
    "persistence",
] }
android-activity = { version = "0.6", features = ["native-activity"] }
